# generated by cabal-rpm-2.0.11 --standalone
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

%global ghc_prefix ghc8.10
%bcond_with compiler_default

%if %{without compiler_default}
%global ghc_version_override 8.10.7
%endif

%global ghc_without_dynamic 1
%global ghc_without_shared 1
%undefine with_ghc_prof
%undefine with_haddock
%global without_prof 1
%global without_haddock 1
%global debug_package %{nil}

%global pkg_name haskell-language-server
%global pkgver %{pkg_name}-%{version}

Name:           %{pkg_name}-%{ghc_prefix}
Version:        1.7.0.0
Release:        1%{?dist}
Summary:        Haskell LSP server for GHC

License:        ASL 2.0
Url:            https://hackage.haskell.org/package/%{pkg_name}
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz
# End cabal-rpm sources
Patch0:         haskell-language-server-1.7.0.0-prettyprinter-1.7.patch

BuildRequires:  cabal-install
BuildRequires:  %{ghc_prefix}
%if %{with compiler_default}
BuildRequires:  %{ghc_prefix}-compiler-default
%endif
BuildRequires:  ghc-rpm-macros
BuildRequires:  zlib-devel
Recommends: haskell-language-server-wrapper-%{ghc_prefix} = %{version}-%{release}
Recommends: %{ghc_prefix} = %{ghc_version}
Recommends: cabal-install
Recommends: stack
Obsoletes:  haskell-language-server-8.10.7 <= 1.7.0.0

%description
The Haskell language server (LSP) built for GHC %{ghc_version}.

Please see the README on GitHub at
<https://github.com/haskell/haskell-language-server#readme>.


%package -n haskell-language-server-wrapper-%{ghc_prefix}
Summary:    LSP server for GHC
Recommends: %{name} = %{version}

%description -n haskell-language-server-wrapper-%{ghc_prefix}
The Haskell language server (LSP) wrapper built by %{ghc_prefix}.

Please see the README on GitHub at
<https://github.com/haskell/haskell-language-server#readme>.


%prep
# Begin cabal-rpm setup:
%setup -q -n %{pkgver}
# End cabal-rpm setup
%patch0 -p1 -b .orig
cabal-tweak-flag dynamic False


%build
# Begin cabal-rpm build:
cabal update
# End cabal-rpm build


%install
%ghc_set_gcc_flags
# Begin cabal-rpm install
mkdir -p %{buildroot}%{_bindir}
cabal install %{!?_with_compiler_default:-w ghc-%{ghc_version}} --install-method=copy --enable-executable-stripping --installdir=%{buildroot}%{_bindir}
# End cabal-rpm install
mv %{buildroot}%{_bindir}/%{pkg_name}{,-%{ghc_version}}


%files
%license LICENSE
%doc ChangeLog.md README.md
%{_bindir}/%{pkg_name}-%{ghc_version}


%files -n haskell-language-server-wrapper-%{ghc_prefix}
%license LICENSE
%doc ChangeLog.md README.md
%{_bindir}/haskell-language-server-wrapper


%changelog
* Thu Apr 28 2022 Jens Petersen <petersen@redhat.com> - 1.7.0.0-1
- https://hackage.haskell.org/package/haskell-language-server-1.7.0.0/changelog
